import type { Need } from './mock-data';

const h = (hrs: number) => new Date(Date.now() - hrs * 3600000);

export const extraNeeds: Need[] = [
  // ═══ EARTHQUAKE — Gujarat ═══
  { id:'n-100', type:'Earthquake Relief', title:'7.1 Earthquake — Bhuj Collapsed Buildings', location:'Bhuj City Center', district:'Kutch', lat:23.2420, lng:69.6669, urgency:'critical', score:99, status:'in-progress', families:4200, description:'Magnitude 7.1 earthquake. 200+ buildings collapsed in Bhuj center. Estimated 4200 families displaced. NDRF teams en route. Heavy machinery required for rubble clearing.', rawReport:'Bhuj 7.1 earthquake hit 3hrs ago. Over 200 buildings down. 4200 families homeless. People trapped. NDRF coming but need more machinery and medical.', reportedAt:h(3), assignedVolunteerIds:['v-020','v-021'] },
  { id:'n-101', type:'Search & Rescue', title:'Trapped survivors — Gandhidham aftershock zone', location:'Gandhidham Industrial Area', district:'Kutch', lat:23.0753, lng:70.1337, urgency:'critical', score:97, status:'in-progress', families:850, description:'Aftershocks continue. Factory building collapsed trapping 40+ workers. Rescue dogs and thermal imaging scanners needed urgently.', rawReport:'Gandhidham factory collapse after aftershock. 40 workers stuck under rubble. Dogs and thermal scanners needed. Ambulances on standby.', reportedAt:h(2), assignedVolunteerIds:['v-022'] },
  { id:'n-102', type:'Medical Aid', title:'Mass casualty triage — Anjar field hospital', location:'Anjar Relief Camp', district:'Kutch', lat:23.1122, lng:70.0249, urgency:'critical', score:96, status:'unassigned', families:1800, description:'Field hospital set up at Anjar school. 300+ injuries, 45 critical surgeries pending. Blood bank supplies critically low. Need surgeons and O-negative blood.', rawReport:'Anjar field hospital overwhelmed. 300 injuries, 45 need surgery now. Blood running out especially O-neg. Send surgeons and blood supplies.', reportedAt:h(2.5), assignedVolunteerIds:[] },

  // ═══ CYCLONE BIPARJOY — Odisha/AP ═══
  { id:'n-110', type:'Cyclone Response', title:'Cyclone Biparjoy — Puri coastal devastation', location:'Puri Coastal Belt', district:'Puri', lat:19.8135, lng:85.8312, urgency:'critical', score:98, status:'in-progress', families:12000, description:'Category 4 cyclone made landfall near Puri. 12,000 families affected. Storm surge 4m. Complete power failure. Fishing boats destroyed. Massive relief operation underway.', rawReport:'Cyclone Biparjoy Cat 4 hit Puri coast. 12000 families affected. 4m storm surge. No power. Fishing boats gone. Need massive relief.', reportedAt:h(6), assignedVolunteerIds:['v-025','v-026','v-027'] },
  { id:'n-111', type:'Shelter', title:'Emergency evacuation shelters — Bhubaneswar', location:'Bhubaneswar Relief Centers', district:'Khordha', lat:20.2961, lng:85.8245, urgency:'critical', score:93, status:'assigned', families:8500, description:'85 cyclone shelters at capacity. 8500 families need temporary housing. Schools and community halls being converted. Tarpaulins, cots, and blankets desperately needed.', rawReport:'Bhubaneswar 85 shelters full. 8500 families still displaced. Converting schools. Need tarps, cots, blankets urgently.', reportedAt:h(5), assignedVolunteerIds:['v-028'] },
  { id:'n-112', type:'Food Distribution', title:'Mass feeding — Konark to Chilika coastal belt', location:'Konark-Chilika Corridor', district:'Puri', lat:19.8876, lng:86.0945, urgency:'high', score:88, status:'unassigned', families:15000, description:'150km coastal stretch without food supply. Fishing communities lost all stored food. 15,000 families need cooked meals and dry rations for 2 weeks minimum.', rawReport:'Konark to Chilika 150km coast no food. Fishermen lost everything. 15000 families need food — cooked meals now, dry rations for 2 weeks.', reportedAt:h(5), assignedVolunteerIds:[] },

  // ═══ FLOODS — Assam/Bihar ═══
  { id:'n-120', type:'Flood Rescue', title:'Brahmaputra breach — Majuli Island submerged', location:'Majuli Island', district:'Majuli', lat:26.9500, lng:94.1667, urgency:'critical', score:95, status:'in-progress', families:6200, description:'Brahmaputra breached embankment. Majuli Island 70% submerged. 6200 families stranded on rooftops. Boats and helicopters needed for evacuation. Cultural heritage sites at risk.', rawReport:'Majuli Island 70% underwater. Brahmaputra embankment broke. 6200 families on rooftops. Need boats and helicopters for rescue. Heritage temples flooding.', reportedAt:h(4), assignedVolunteerIds:['v-030'] },
  { id:'n-121', type:'Water Supply', title:'Contaminated water crisis — Darbhanga', location:'Darbhanga Municipal', district:'Darbhanga', lat:26.1542, lng:85.8918, urgency:'high', score:84, status:'unassigned', families:3400, description:'Flood waters mixed with sewage contaminated drinking water sources. 3400 families at risk of cholera outbreak. Water purification tablets and RO units needed.', rawReport:'Darbhanga water supply contaminated by flood sewage. 3400 families drinking bad water. Cholera risk high. Need purification tabs and RO units.', reportedAt:h(10), assignedVolunteerIds:[] },
  { id:'n-122', type:'Animal Rescue', title:'Kaziranga rhino rescue — flooded sanctuaries', location:'Kaziranga National Park', district:'Golaghat', lat:26.5775, lng:93.1711, urgency:'high', score:80, status:'in-progress', families:0, description:'Kaziranga 80% flooded. One-horned rhinos, elephants, and tigers moving to highlands and crossing NH-37. Veterinary teams and wildlife rescue boats needed.', rawReport:'Kaziranga 80% flooded. Rhinos crossing highway. Tigers spotted near villages. Need vet teams and wildlife rescue boats. Animals drowning.', reportedAt:h(8), assignedVolunteerIds:['v-031'] },

  // ═══ HEATWAVE — Rajasthan/UP ═══
  { id:'n-130', type:'Heatwave Relief', title:'Extreme heatwave 48°C — Churu district', location:'Churu Town', district:'Churu', lat:28.3039, lng:74.9672, urgency:'critical', score:92, status:'unassigned', families:5600, description:'Temperature 48.2°C for 5 consecutive days. 23 heat stroke deaths confirmed. 5600 families without cooling facilities. ORS packets, water coolers, and shade structures needed.', rawReport:'Churu 48.2C for 5 days. 23 dead from heatstroke. 5600 families suffering. Need ORS, water coolers, shade tents. Hospitals full of heat patients.', reportedAt:h(1), assignedVolunteerIds:[] },
  { id:'n-131', type:'Medical Aid', title:'Heatstroke mass casualty — Varanasi ghats', location:'Varanasi Dashashwamedh area', district:'Varanasi', lat:25.3176, lng:83.0101, urgency:'high', score:85, status:'in-progress', families:2200, description:'Pilgrims and laborers collapsing at ghats. 140+ heatstroke cases in 48hrs. BHU hospital overflow. Mobile medical units and IV fluids needed.', rawReport:'Varanasi ghats — pilgrims fainting from heat. 140 heatstroke cases in 2 days. BHU hospital full. Need mobile medical vans and IV drips.', reportedAt:h(6), assignedVolunteerIds:['v-033'] },

  // ═══ INDUSTRIAL / CHEMICAL ═══
  { id:'n-140', type:'Chemical Spill', title:'Gas leak — Visakhapatnam industrial zone', location:'Vizag Industrial Area RR Venkatapuram', district:'Visakhapatnam', lat:17.7500, lng:83.3500, urgency:'critical', score:97, status:'in-progress', families:3200, description:'Styrene gas leak from chemical plant. 3200 families in 5km radius evacuated. 11 deaths, 800+ hospitalized. Hazmat teams and gas masks needed for containment.', rawReport:'Vizag styrene gas leak from plant. 3200 families evacuated 5km radius. 11 dead 800 in hospital. Need hazmat teams and gas masks for containment.', reportedAt:h(1.5), assignedVolunteerIds:['v-035','v-036'] },

  // ═══ EPIDEMIC — Kerala ═══
  { id:'n-150', type:'Epidemic Control', title:'Nipah virus outbreak — Kozhikode cluster', location:'Kozhikode Medical College zone', district:'Kozhikode', lat:11.2588, lng:75.7804, urgency:'critical', score:94, status:'in-progress', families:1500, description:'Nipah virus cluster detected. 8 confirmed cases, 2 deaths. 1500 families in containment zone. Contact tracing for 400+ people. PPE kits, isolation wards, and epidemiologists needed.', rawReport:'Kozhikode Nipah confirmed 8 cases 2 deaths. 1500 families locked down. Tracing 400 contacts. Need PPE kits, isolation wards, epidemiologists.', reportedAt:h(12), assignedVolunteerIds:['v-037'] },

  // ═══ LANDSLIDE — Uttarakhand/Himachal ═══
  { id:'n-160', type:'Landslide Clearance', title:'Massive landslide — Joshimath sinking', location:'Joshimath Town', district:'Chamoli', lat:30.5550, lng:79.5639, urgency:'critical', score:93, status:'in-progress', families:4800, description:'Entire hillside collapsed blocking Badrinath highway. 680 houses developed cracks. 4800 families evacuated. ITBP and SDRF conducting rescue. Geologists assessing subsidence.', rawReport:'Joshimath massive landslide. 680 houses cracking. 4800 families evacuated. Highway to Badrinath blocked. ITBP and SDRF on ground. Need geologists.', reportedAt:h(8), assignedVolunteerIds:['v-038','v-039'] },
  { id:'n-161', type:'Road Clearance', title:'NH-5 blocked — Shimla-Chandigarh landslide', location:'Shimla-Chandigarh NH-5 KM 84', district:'Solan', lat:30.9084, lng:77.0900, urgency:'high', score:79, status:'assigned', families:0, description:'Landslide debris covering 200m of NH-5. 2000+ vehicles stranded. Alternative route via Nalagarh 6hrs longer. BRO team clearing but need heavy excavators.', rawReport:'NH-5 Shimla road blocked KM 84 landslide. 200m debris. 2000 vehicles stuck. BRO clearing slowly. Need big excavators.', reportedAt:h(14), assignedVolunteerIds:['v-040'] },

  // ═══ TSUNAMI WARNING — Tamil Nadu ═══
  { id:'n-170', type:'Tsunami Response', title:'Tsunami alert — Nagapattinam coastal evacuation', location:'Nagapattinam Coast', district:'Nagapattinam', lat:10.7672, lng:79.8449, urgency:'high', score:86, status:'in-progress', families:9000, description:'7.8 undersea earthquake near Andaman triggered tsunami warning. 9000 families being evacuated from Nagapattinam coast. Sirens active. Schools converted to shelters.', rawReport:'Tsunami warning Nagapattinam after 7.8 earthquake. 9000 families evacuating. Sirens on. Schools becoming shelters. Need buses and volunteers for evacuation.', reportedAt:h(1), assignedVolunteerIds:['v-041','v-042'] },

  // ═══ FIRE — Delhi/Mumbai ═══
  { id:'n-180', type:'Fire Response', title:'Massive warehouse fire — Mundka Industrial', location:'Mundka Industrial Area', district:'West Delhi', lat:28.6845, lng:76.9739, urgency:'critical', score:91, status:'in-progress', families:200, description:'4-story warehouse fire with 200+ workers trapped. 15 fire tenders deployed. Building has single exit staircase. 35 rescued so far. Firefighters and ambulances needed.', rawReport:'Mundka warehouse 4 floors on fire. 200 workers trapped. Only one staircase. 15 fire trucks there. 35 saved so far. Need more firefighters and ambulances.', reportedAt:h(0.5), assignedVolunteerIds:['v-043'] },

  // ═══ CHILD PROTECTION — Sensitive ═══
  { id:'n-190', type:'Child Protection', title:'Orphaned children — post-flood Wayanad', location:'Wayanad District', district:'Wayanad', lat:11.6854, lng:76.1320, urgency:'high', score:83, status:'assigned', families:45, description:'Devastating landslides orphaned 67 children. Child welfare committee activated. Need temporary foster care, trauma counselors, and child-safe shelter spaces.', rawReport:'Wayanad landslide — 67 children orphaned. CWC activated but overwhelmed. Need foster families, trauma counselors, child-safe shelters urgently.', reportedAt:h(48), assignedVolunteerIds:['v-044'] },

  // ═══ MENTAL HEALTH — Sensitive ═══
  { id:'n-191', type:'Mental Health', title:'PTSD support — earthquake survivors Manipur', location:'Imphal East District', district:'Imphal East', lat:24.8170, lng:93.9368, urgency:'high', score:76, status:'unassigned', families:1200, description:'Post-earthquake PTSD affecting 1200 families. Survivors refusing to enter buildings. Children showing acute anxiety. Psychologists and trauma counselors urgently needed.', rawReport:'Imphal earthquake survivors PTSD. 1200 families affected. People sleeping outdoors afraid of buildings. Children very anxious. Need psychologists.', reportedAt:h(72), assignedVolunteerIds:[] },

  // ═══ NORMAL / COMMUNITY NEEDS ═══
  { id:'n-200', type:'Food Distribution', title:'Mid-day meal disruption — Jharkhand tribal belt', location:'Ranchi Tribal Area', district:'Ranchi', lat:23.3441, lng:85.3096, urgency:'medium', score:58, status:'unassigned', families:420, description:'School mid-day meal supply chain broken for 3 weeks. 420 tribal families relying on school meals for children. Rice and dal stocks exhausted.', rawReport:'Ranchi tribal schools no mid-day meals for 3 weeks. 420 families affected. Kids going hungry. Rice and dal finished. Supply truck not coming.', reportedAt:h(72), assignedVolunteerIds:[] },
  { id:'n-201', type:'Sanitation', title:'Open defecation crisis — Muzaffarpur villages', location:'Muzaffarpur Rural Block', district:'Muzaffarpur', lat:26.1209, lng:85.3647, urgency:'medium', score:45, status:'unassigned', families:600, description:'Toilet construction stalled. 600 families without sanitation. Monsoon approaching increases disease risk. Need masons, materials, and health awareness drive.', rawReport:'Muzaffarpur village toilets construction stopped. 600 families no toilets. Monsoon coming, disease risk high. Need masons and toilet materials.', reportedAt:h(120), assignedVolunteerIds:[] },
  { id:'n-202', type:'Communication', title:'Network blackout — Arunachal border villages', location:'Tawang District Villages', district:'Tawang', lat:27.5860, lng:91.8594, urgency:'medium', score:52, status:'assigned', families:350, description:'Cell towers damaged by snowfall. 12 border villages without communication for 10 days. Army relay radio being set up. Satellite phones needed for medical emergencies.', rawReport:'Tawang 12 villages no mobile network 10 days. Snow damaged towers. Army setting radio. Need satellite phones for medical emergencies.', reportedAt:h(240), assignedVolunteerIds:['v-045'] },
  { id:'n-203', type:'Clothing', title:'Blanket drive — Ladakh winter emergency', location:'Leh District Remote Villages', district:'Leh', lat:34.1526, lng:77.5771, urgency:'medium', score:60, status:'in-progress', families:280, description:'Temperatures -25°C. Remote villages running low on fuel and blankets. Elderly and children at hypothermia risk. Warm clothing and kerosene needed.', rawReport:'Leh remote villages -25C. Running out of blankets and kerosene. Old people and kids at risk. Need warm clothes and fuel delivered.', reportedAt:h(48), assignedVolunteerIds:['v-046'] },
  { id:'n-204', type:'Water Supply', title:'Fluoride contamination — Nalgonda wells', location:'Nalgonda District', district:'Nalgonda', lat:17.0575, lng:79.2690, urgency:'medium', score:55, status:'unassigned', families:900, description:'Groundwater fluoride levels 5x safe limit. 900 families showing dental fluorosis. Need RO plants and alternative water source pipeline from Krishna river.', rawReport:'Nalgonda well water fluoride very high. 900 families teeth getting damaged. Need RO plants or pipeline from Krishna river.', reportedAt:h(168), assignedVolunteerIds:[] },

  // ═══ RESOLVED — Success stories ═══
  { id:'n-300', type:'Cyclone Response', title:'Cyclone Amphan recovery — Sundarbans restored', location:'South 24 Parganas', district:'South 24 Parganas', lat:21.8682, lng:88.4244, urgency:'resolved', score:90, status:'resolved', families:18000, description:'Post-cyclone reconstruction complete. 18,000 families rehoused. Embankments rebuilt. Mangrove replantation drive finished. Fishing boats replaced.', rawReport:'Sundarbans Amphan recovery done. 18000 families rehoused. Embankments fixed. Mangroves replanted. New fishing boats distributed.', reportedAt:h(720), resolvedAt:h(168), assignedVolunteerIds:['v-025','v-028'] },
  { id:'n-301', type:'Earthquake Relief', title:'Sikkim earthquake rehabilitation complete', location:'Gangtok District', district:'East Sikkim', lat:27.3389, lng:88.6065, urgency:'resolved', score:85, status:'resolved', families:2400, description:'All 2400 displaced families relocated to permanent earthquake-resistant housing. Schools and hospitals rebuilt. Seismic monitoring stations installed.', rawReport:'Sikkim earthquake rehab complete. 2400 families in new quake-proof houses. Schools and hospitals rebuilt. Seismic monitors installed.', reportedAt:h(2160), resolvedAt:h(720), assignedVolunteerIds:['v-038','v-040'] },
  { id:'n-302', type:'Epidemic Control', title:'COVID cluster contained — Dharavi success', location:'Dharavi, Mumbai', district:'Mumbai', lat:19.0438, lng:72.8534, urgency:'resolved', score:88, status:'resolved', families:5000, description:'Dharavi COVID cluster fully contained through aggressive contact tracing, community health workers, and door-to-door screening of 5000 families. Zero new cases for 28 days.', rawReport:'Dharavi COVID cluster zero cases 28 days. Contact tracing worked. 5000 families screened. Community health workers did great job.', reportedAt:h(1440), resolvedAt:h(672), assignedVolunteerIds:['v-037','v-033'] },
  { id:'n-303', type:'Flood Rescue', title:'Kerala floods — Wayanad rebuilt', location:'Wayanad District', district:'Wayanad', lat:11.6854, lng:76.1320, urgency:'resolved', score:82, status:'resolved', families:3200, description:'Complete rehabilitation of 3200 flood-affected families. New houses with raised foundations built. Community rain-water harvesting system installed.', rawReport:'Wayanad flood rehab done. 3200 families in new houses. Raised foundations. Rain water harvesting installed across villages.', reportedAt:h(2880), resolvedAt:h(1440), assignedVolunteerIds:['v-044','v-041'] },
];
